
import React, { useState, useMemo } from 'react';
import { Patient, Medication, FieldSettings, User } from '../types';
import { X, Pill, Printer, AlertTriangle, ShieldAlert, Lock } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface EPrescriptionModalProps {
    isOpen: boolean;
    onClose: () => void;
    patient: Patient;
    fieldSettings: FieldSettings;
    currentUser: User;
}

const EPrescriptionModal: React.FC<EPrescriptionModalProps> = ({ isOpen, onClose, patient, fieldSettings, currentUser }) => {
    const [selectedMedId, setSelectedMedId] = useState<string>('');
    const [dosage, setDosage] = useState('');
    const [instructions, setInstructions] = useState('');
    const [quantity, setQuantity] = useState('');
    
    const medications = fieldSettings.medications || [];
    const selectedMed = useMemo(() => medications.find(m => m.id === selectedMedId), [selectedMedId, medications]);

    const handleMedicationSelect = (medId: string) => {
        setSelectedMedId(medId);
        const med = medications.find(m => m.id === medId);
        if (med) {
            setDosage(med.dosage);
            setInstructions(med.instructions);
        } else {
            setDosage('');
            setInstructions('');
        }
    };
    
    const allergyConflict = useMemo(() => {
        if (!selectedMedId || !patient.allergies) return null;
        const med = medications.find(m => m.id === selectedMedId);
        if (!med || !med.contraindicatedAllergies) return null;

        const patientAllergies = patient.allergies.map(a => a.toLowerCase());
        const conflict = med.contraindicatedAllergies.find(ca => patientAllergies.includes(ca.toLowerCase()));
        
        return conflict || null;
    }, [selectedMedId, patient.allergies, medications]);

    // --- PDA GOLD STANDARD: S2 GUARD ---
    const s2Violation = useMemo(() => {
        return selectedMed?.isS2Controlled && !currentUser.s2License;
    }, [selectedMed, currentUser.s2License]);

    const handlePrint = () => {
        if (!selectedMed) return;
        if (s2Violation) return; // Hard stop

        const doc = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a5' // Classic prescription pad size
        });

        // Header
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text(currentUser.name.toUpperCase(), 74, 20, { align: 'center' });
        
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(currentUser.specialization || 'General Dentistry', 74, 26, { align: 'center' });
        
        doc.setFontSize(9);
        doc.text(`PRC No: ${currentUser.prcLicense}  |  PTR No: ${currentUser.ptrNumber}`, 74, 32, { align: 'center' });
        if (currentUser.s2License) {
            doc.text(`PDEA S2: ${currentUser.s2License}`, 74, 37, { align: 'center' });
        }

        // S2 Warning Banner
        if (selectedMed.isS2Controlled) {
            doc.setFontSize(10);
            doc.setTextColor(128, 0, 128); // Purple
            doc.text("CONTROLLED SUBSTANCE - YELLOW PRESCRIPTION REQUIRED", 74, 45, { align: 'center' });
            doc.setTextColor(0, 0, 0);
        }

        // Line
        doc.setLineWidth(0.5);
        doc.line(15, 50, 133, 50);

        // Patient Details
        doc.setFontSize(11);
        doc.text(`Patient: ${patient.name}`, 15, 60);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 15, 66);
        doc.text(`Age: ${patient.age || '-'}   Sex: ${patient.sex || '-'}`, 15, 72);

        // Rx Symbol
        doc.setFont('times', 'bolditalic');
        doc.setFontSize(40);
        doc.text("Rx", 15, 90);

        // Meds
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.text(`${selectedMed.name} ${dosage}`, 25, 95);
        
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(12);
        doc.text(`Disp: #${quantity}`, 25, 105);
        
        doc.setFont('helvetica', 'italic');
        doc.text(`Sig: ${instructions}`, 25, 115);

        // Footer / Signature
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.line(80, 170, 133, 170);
        doc.text("Prescriber's Signature", 106, 175, { align: 'center' });
        
        // LEGAL DISCLAIMER
        doc.setFontSize(7);
        doc.setTextColor(100, 100, 100);
        doc.text("This electronic prescription must be validated with a wet signature unless", 74, 195, { align: 'center' });
        doc.text("transmitted via a DOH-accredited e-prescription system. (R.A. 8792 / DDB)", 74, 198, { align: 'center' });
        
        // --- DPA FOOTER ---
        doc.text(`CONFIDENTIAL RECORD. Generated by ${currentUser.name} on ${new Date().toLocaleString()}. Uncontrolled when printed.`, 74, 205, { align: 'center' });

        doc.save(`Rx_${patient.surname}_${selectedMed.name}.pdf`);
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-[70] flex justify-center items-center p-4">
            <div className="bg-white w-full max-w-lg rounded-3xl shadow-2xl flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-300">
                <div className="p-6 border-b border-slate-100 flex justify-between items-center shrink-0">
                    <div className="flex items-center gap-3">
                        <div className="bg-teal-100 p-3 rounded-xl text-teal-700"><Pill size={24} /></div>
                        <div>
                            <h2 className="text-xl font-bold text-slate-800">New e-Prescription</h2>
                            <p className="text-sm text-slate-500">For: {patient.name}</p>
                        </div>
                    </div>
                    <button onClick={onClose}><X size={24} className="text-slate-500" /></button>
                </div>

                <div className="flex-1 overflow-y-auto p-6 space-y-4 bg-slate-50/50">
                    {allergyConflict && (
                        <div className="bg-red-100 border-l-4 border-red-500 text-red-800 p-4 rounded-r-lg shadow-md" role="alert">
                            <div className="flex items-center gap-3">
                                <AlertTriangle size={24} />
                                <div>
                                    <p className="font-bold">Critical Allergy Alert</p>
                                    <p className="text-sm">Patient has a recorded allergy to <strong className="uppercase">{allergyConflict}</strong>.</p>
                                </div>
                            </div>
                        </div>
                    )}

                    {s2Violation && (
                         <div className="bg-lilac-100 border-l-4 border-lilac-600 text-lilac-900 p-4 rounded-r-lg shadow-md" role="alert">
                            <div className="flex items-center gap-3">
                                <Lock size={24} />
                                <div>
                                    <p className="font-bold">S2 License Verification Failed</p>
                                    <p className="text-sm">This is a controlled substance. You must add your <strong>PDEA S2 License</strong> to your user profile to prescribe this medication.</p>
                                </div>
                            </div>
                        </div>
                    )}

                    <div>
                        <label className="label">Medication</label>
                        <select value={selectedMedId} onChange={e => handleMedicationSelect(e.target.value)} className="input">
                            <option value="">Select from formulary...</option>
                            {medications.map(med => (
                                <option key={med.id} value={med.id}>
                                    {med.name} {med.isS2Controlled ? '(S2 CONTROLLED)' : ''}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div className="grid grid-cols-3 gap-4">
                        <div className="col-span-2">
                            <label className="label">Dosage</label>
                            <input type="text" value={dosage} onChange={e => setDosage(e.target.value)} className="input" />
                        </div>
                        <div>
                            <label className="label">Quantity (#)</label>
                            <input type="number" value={quantity} onChange={e => setQuantity(e.target.value)} className="input" />
                        </div>
                    </div>

                    <div>
                        <label className="label">Instructions (Sig.)</label>
                        <textarea value={instructions} onChange={e => setInstructions(e.target.value)} className="input h-24" />
                    </div>
                    
                    <div className="bg-slate-100 p-3 rounded-lg text-[10px] text-slate-500 italic border border-slate-200">
                        * A legal disclaimer regarding wet signature requirements will be automatically appended to the PDF output.
                    </div>
                </div>

                <div className="p-4 bg-white border-t border-slate-100 flex justify-end gap-3">
                    <button onClick={onClose} className="px-6 py-3 bg-slate-100 text-slate-700 rounded-xl font-bold">Cancel</button>
                    <button 
                        onClick={handlePrint} 
                        disabled={!selectedMedId || !quantity || !!s2Violation} 
                        className={`px-8 py-3 rounded-xl font-bold flex items-center gap-2 transition-all ${s2Violation ? 'bg-slate-200 text-slate-400' : 'bg-teal-600 text-white hover:bg-teal-700 shadow-lg shadow-teal-600/20'}`}
                    >
                        <Printer size={20} /> 
                        {selectedMed?.isS2Controlled ? 'Generate Controlled Rx' : 'Generate Prescription'}
                    </button>
                </div>
            </div>
            <style>{`.label { font-size: 0.875rem; font-weight: 600; color: #334155; margin-bottom: 0.5rem; display: block; } .input { width: 100%; padding: 0.75rem; border: 1px solid #cbd5e1; border-radius: 0.5rem; background: #fff; }`}</style>
        </div>
    );
};

export default EPrescriptionModal;
