import React, { useState, useMemo, useEffect } from 'react';
import { Search, Phone, MessageSquare, ChevronRight, X, UserPlus, AlertTriangle, Shield, Heart, Activity, Hash, Plus, Trash2, CalendarPlus, Pencil, Printer, CheckCircle, FileCheck, ChevronDown, ChevronUp, AlertCircle, Download, Pill, Cigarette, Baby, User as UserIcon, MapPin, Briefcase, Users, CreditCard, Stethoscope, Mail, Clock, FileText, Grid, List, ClipboardList, DollarSign, StickyNote, PenLine, DownloadCloud, Archive, FileImage, FileUp, FileSignature, ShieldCheck, Lock, Megaphone, BellOff, ArrowRightLeft } from 'lucide-react';
import { Patient, Appointment, User, UserRole, DentalChartEntry, TreatmentStatus, FieldSettings, PerioMeasurement, AuditLogEntry, PatientFile, AppointmentStatus, LedgerEntry, ClinicalProtocolRule } from '../types';
import Fuse from 'fuse.js';
import Odontogram from './Odontogram';
import Odontonotes from './Odontonotes';
import TreatmentPlan from './TreatmentPlan';
import PerioChart from './PerioChart';
import PatientLedger from './PatientLedger';
import ConsentCaptureModal from './ConsentCaptureModal';
import EPrescriptionModal from './EPrescriptionModal';
import ProtocolOverrideModal from './ProtocolOverrideModal'; 
import { formatDate } from '../constants';
import { useToast } from './ToastSystem';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { getTrustedTime } from '../services/timeService';

interface PatientListProps {
  patients: Patient[];
  appointments: Appointment[];
  currentUser: User;
  selectedPatientId: string | null;
  onSelectPatient: (id: string | null) => void;
  onAddPatient: () => void;
  onEditPatient: (patient: Patient) => void;
  onQuickUpdatePatient: (patient: Patient) => void;
  onBulkUpdatePatients?: (patients: Patient[]) => void;
  onDeletePatient: (patientId: string) => void;
  onBookAppointment: (patientId: string) => void;
  fieldSettings?: FieldSettings; 
  logAction: (action: AuditLogEntry['action'], entity: AuditLogEntry['entity'], entityId: string, details: string, previousState?: any, newState?: any) => void;
  onPreparePhilHealthClaim?: (ledgerEntry: LedgerEntry, procedureName: string) => void;
  onCreateClaim?: (patientId: string, ledgerEntryId: string, provider: string, amount: number, type: 'HMO' | 'PhilHealth') => void;
}

const generatePatientPDF = (patient: Patient, currentUser: User, logAction: any) => {
    const doc = new jsPDF();
    const primaryColor = [13, 148, 136]; 

    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, 210, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text("PATIENT CLINICAL RECORD", 14, 20);
    
    const pageCount = doc.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor(150);
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.text(`CONFIDENTIAL MEDICAL RECORD. Generated by ${currentUser.name} on ${new Date().toLocaleString()}.`, 105, 290, { align: 'center' });
    }

    doc.save(`Record_${patient.surname}_${patient.id}.pdf`);
    logAction('EXPORT_RECORD', 'Patient', patient.id, 'User exported full clinical record to PDF.');
};

const ImagingGallery = ({ files }: { files: PatientFile[] }) => {
    const [compareMode, setCompareMode] = useState(false);
    const [selection, setSelection] = useState<string[]>([]);
    const xrays = files.filter(f => f.category === 'X-Ray');

    const toggleSelect = (id: string) => {
        if (selection.includes(id)) {
            setSelection(selection.filter(s => s !== id));
        } else if (selection.length < 2) {
            setSelection([...selection, id]);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                <h4 className="font-bold text-slate-800 flex items-center gap-2 text-sm uppercase tracking-wider"><FileImage className="text-teal-600"/> Radiology & Imaging Gallery</h4>
                <button 
                    onClick={() => { setCompareMode(!compareMode); setSelection([]); }}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-2 border shadow-sm
                        ${compareMode ? 'bg-lilac-600 text-white border-lilac-400' : 'bg-white text-slate-500 border-slate-200 hover:bg-slate-50'}
                    `}
                >
                    <ArrowRightLeft size={16}/> {compareMode ? 'Exit Comparison' : 'Compare Side-by-Side'}
                </button>
            </div>

            {compareMode && selection.length > 0 && (
                <div className="grid grid-cols-2 gap-4 h-[400px] animate-in slide-in-from-top-4 duration-500">
                    {selection.map(id => (
                        <div key={id} className="bg-black rounded-3xl overflow-hidden relative border-4 border-lilac-400 shadow-2xl">
                            <img src={xrays.find(x => x.id === id)?.url} className="w-full h-full object-contain" />
                            <div className="absolute top-4 left-4 bg-black/60 backdrop-blur-md text-white px-3 py-1.5 rounded-xl text-[10px] font-bold uppercase tracking-widest border border-white/20">
                                {xrays.find(x => x.id === id)?.title}
                            </div>
                        </div>
                    ))}
                    {selection.length < 2 && (
                        <div className="border-4 border-dashed border-slate-200 rounded-3xl flex flex-col items-center justify-center text-slate-400 text-sm font-bold bg-slate-50/50">
                            <Plus size={32} className="mb-2 opacity-30"/>
                            Select 2nd Image to Monitor Progression
                        </div>
                    )}
                </div>
            )}

            <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
                {xrays.map(file => (
                    <div 
                        key={file.id} 
                        onClick={() => compareMode && toggleSelect(file.id)}
                        className={`group relative aspect-square rounded-2xl border-2 transition-all overflow-hidden cursor-pointer shadow-sm
                            ${selection.includes(file.id) ? 'border-lilac-500 ring-4 ring-lilac-500/20 scale-[0.98]' : 'border-slate-100 hover:border-teal-300 hover:shadow-lg'}
                        `}
                    >
                        <img src={file.url} className="w-full h-full object-cover grayscale group-hover:grayscale-0 transition-all duration-500" />
                        <div className="absolute inset-x-0 bottom-0 bg-slate-900/60 backdrop-blur-sm p-3 text-white transform translate-y-full group-hover:translate-y-0 transition-transform duration-300">
                            <p className="text-[10px] font-bold truncate uppercase">{file.title}</p>
                            <p className="text-[8px] opacity-70 font-mono">{formatDate(file.uploadedAt)}</p>
                        </div>
                        {compareMode && (
                             <div className={`absolute top-2 right-2 w-6 h-6 rounded-full border-2 flex items-center justify-center transition-all ${selection.includes(file.id) ? 'bg-lilac-500 border-lilac-500 text-white' : 'bg-white/80 backdrop-blur-sm border-white'}`}>
                                {selection.includes(file.id) && <CheckCircle size={14} strokeWidth={3} />}
                             </div>
                        )}
                    </div>
                ))}
            </div>
        </div>
    );
};

const PatientList: React.FC<PatientListProps> = ({ 
    patients, appointments, currentUser, selectedPatientId, onSelectPatient, onAddPatient, onEditPatient,
    onQuickUpdatePatient, onBulkUpdatePatients, onDeletePatient, onBookAppointment, fieldSettings, logAction, onPreparePhilHealthClaim, onCreateClaim
}) => {
  const toast = useToast();
  const [activeTab, setActiveTab] = useState<'info' | 'medical' | 'chart' | 'perio' | 'plan' | 'ledger' | 'documents' | 'imaging'>('info'); 
  const [showNeedsPrintingOnly, setShowNeedsPrintingOnly] = useState(false);
  const [showArchived, setShowArchived] = useState(false);
  const [chartViewMode, setChartViewMode] = useState<'visual' | 'notes'>('visual');
  const [isEPrescriptionModalOpen, setIsEPrescriptionModalOpen] = useState(false);
  const [editingTooth, setEditingTooth] = useState<number | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [stagedSoapPrefill, setStagedSoapPrefill] = useState<Partial<DentalChartEntry> | null>(null);
  const [pendingClinicalEntry, setPendingClinicalEntry] = useState<DentalChartEntry | null>(null);
  const [safetyAlert, setSafetyAlert] = useState<ClinicalProtocolRule | null>(null);

  const enableCompliance = fieldSettings?.features?.enableComplianceAudit ?? true;
  const selectedPatient = useMemo(() => patients.find(p => p.id === selectedPatientId) || null, [patients, selectedPatientId]);

  const unbilledCount = useMemo(() => {
    return (selectedPatient?.dentalChart || []).filter(e => e.status === 'Completed' && e.price && e.price > 0 && !e.isBilled).length;
  }, [selectedPatient?.dentalChart]);

  useEffect(() => {
    if (selectedPatientId) {
        setActiveTab('info');
        setEditingTooth(null); 
        logAction('VIEW_RECORD', 'Patient', selectedPatientId, `User accessed full clinical record.`);
    }
  }, [selectedPatientId]);

  const filteredPatients = useMemo(() => {
    let result = patients;
    if (!showArchived) result = result.filter(p => !p.isArchived);
    if (showNeedsPrintingOnly && enableCompliance) {
        result = result.filter(p => {
             if (!p.lastDigitalUpdate) return false; 
             if (!p.lastPrintedDate) return true; 
             return new Date(p.lastDigitalUpdate) > new Date(p.lastPrintedDate);
        });
    }
    if (searchTerm) {
        const fuse = new Fuse(result, { keys: ['name', 'firstName', 'surname', 'email', 'phone', 'insuranceProvider', 'id'], threshold: 0.3, distance: 100 });
        result = fuse.search(searchTerm).map(r => r.item);
    }
    return result;
  }, [patients, searchTerm, showNeedsPrintingOnly, showArchived, enableCompliance]);

  const isClinicalReadOnly = currentUser.role === UserRole.DENTAL_ASSISTANT;
  const canDelete = currentUser.role === UserRole.ADMIN || currentUser.role === UserRole.DENTIST;
  const isAdmin = currentUser.role === UserRole.ADMIN;

  const isCritical = (p: Patient) => p.seriousIllness || p.underMedicalTreatment || p.takingMedications || (p.allergies && p.allergies.length > 0 && !p.allergies.includes('None')) || (p.medicalConditions && p.medicalConditions.length > 0 && !p.medicalConditions.includes('None'));
  const isPaperworkPending = (p: Patient) => enableCompliance && p.lastDigitalUpdate && (!p.lastPrintedDate || new Date(p.lastDigitalUpdate) > new Date(p.lastPrintedDate));
  const critical = selectedPatient ? isCritical(selectedPatient) : false;

  const handleSignOffToday = async () => {
      if (!selectedPatient) return;
      const today = new Date().toISOString().split('T')[0];
      const todayEntries = selectedPatient.dentalChart?.filter(e => e.date === today && !e.isLocked) || [];
      if (todayEntries.length === 0) {
          toast.info("No unsigned clinical entries found for today.");
          return;
      }
      if (window.confirm(`Are you sure you want to digitally sign off on today's clinical notes? This will lock ${todayEntries.length} entries.`)) {
          const { timestamp } = await getTrustedTime();
          const updatedChart = selectedPatient.dentalChart?.map(e => {
              if (e.date === today && !e.isLocked) {
                  return { ...e, isLocked: true, lockedInfo: { by: currentUser.name, at: timestamp } };
              }
              return e;
          });
          onQuickUpdatePatient({ ...selectedPatient, dentalChart: updatedChart });
          logAction('SIGN_OFF_RECORD', 'ClinicalNote', selectedPatient.id, `Digitally signed off on today's notes.`);
          toast.success("Record sealed and signed off.");
      }
  };

  const handleOverrideConfirm = (reason: string) => {
      if (!pendingClinicalEntry) return;
      logAction('OVERRIDE_ALERT', 'ClinicalAlert', selectedPatient!.id, `Allergy CDS Overridden for ${pendingClinicalEntry.procedure}. Reason: ${reason}`);
      commitChartEntry(pendingClinicalEntry);
      setSafetyAlert(null);
      setPendingClinicalEntry(null);
  };

  const commitChartEntry = async (entry: DentalChartEntry) => {
      const { timestamp, isVerified } = await getTrustedTime();
      const updatedChart = [...(selectedPatient!.dentalChart || []), { ...entry, timestamp, isVerifiedTimestamp: isVerified }];
      onQuickUpdatePatient({ ...selectedPatient!, dentalChart: updatedChart, lastDigitalUpdate: timestamp });
      toast.success("Entry saved.");
  };

  const toggleMarketingConsent = async () => {
      if (!selectedPatient) return;
      const newVal = !selectedPatient.marketingConsent;
      onQuickUpdatePatient({ ...selectedPatient, marketingConsent: newVal });
      logAction('UPDATE', 'Patient', selectedPatient.id, `Marketing Consent ${newVal ? 'GRANTED' : 'REVOKED'}.`);
  };

  const InfoRow = ({ icon: Icon, label, value, subValue }: { icon: any, label: string, value?: string | number, subValue?: string }) => (
      <div className="flex items-start gap-3 p-3 rounded-lg hover:bg-slate-50 transition-colors">
          <div className="bg-white p-2 rounded-lg border border-slate-100 shadow-sm shrink-0"><Icon size={16} className="text-teal-600" /></div>
          <div><div className="text-xs font-bold text-slate-400 uppercase tracking-wide">{label}</div><div className="font-semibold text-slate-800 text-sm">{value || '-'}</div>{subValue && <div className="text-xs text-slate-500">{subValue}</div>}</div>
      </div>
  );

  return (
    <div className="h-full flex flex-col md:flex-row gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500 relative">
      <div className={`flex-1 bg-white rounded-2xl shadow-sm border border-slate-100 flex flex-col ${selectedPatientId ? 'hidden md:flex' : 'flex'}`}>
        <div className="p-4 border-b border-slate-100 flex justify-between items-center gap-2">
          <div className="flex-1"><h2 className="text-xl font-bold text-slate-800">Registry</h2></div>
          <button onClick={onAddPatient} className="bg-teal-600 hover:bg-teal-700 text-white p-2 rounded-lg transition-colors flex items-center gap-1 text-sm font-medium shadow-sm"><UserPlus size={18} /> <span>New</span></button>
        </div>
        <div className="p-4 pt-2 space-y-2">
            <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input type="text" placeholder="Search..." className="w-full pl-10 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-teal-500/20 focus:border-teal-500 transition-all" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)}/></div>
            <div className="grid grid-cols-2 gap-2">
                 {enableCompliance && (<button onClick={() => setShowNeedsPrintingOnly(!showNeedsPrintingOnly)} className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-xs font-bold border transition-all ${showNeedsPrintingOnly ? 'bg-amber-50 border-amber-200 text-amber-800' : 'bg-white border-slate-200 text-slate-500 hover:bg-slate-50'}`}><div className="flex items-center gap-2"><Printer size={16} /> Needs Printing</div>{showNeedsPrintingOnly && <CheckCircle size={16} />}</button>)}
                 {(isAdmin || currentUser.role === UserRole.DENTIST) && (<button onClick={() => setShowArchived(!showArchived)} className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-xs font-bold border transition-all ${showArchived ? 'bg-slate-200 border-slate-300 text-slate-800' : 'bg-white border-slate-200 text-slate-500 hover:bg-slate-50'}`}><div className="flex items-center gap-2"><Archive size={16} /> Archived</div>{showArchived && <CheckCircle size={16} />}</button>)}
            </div>
        </div>
        <div className="flex-1 overflow-y-auto p-2 space-y-2">
          {filteredPatients.length === 0 ? (<div className="text-center py-8 text-slate-400 italic">No matches.</div>) : (filteredPatients.map(p => (
              <button key={p.id} onClick={() => onSelectPatient(p.id)} className={`w-full text-left p-4 rounded-xl transition-all group flex items-center justify-between border border-transparent ${selectedPatientId === p.id ? 'bg-teal-50 border-teal-100' : 'hover:bg-slate-50 hover:border-slate-100'} ${p.isArchived ? 'opacity-60 bg-slate-100' : ''}`}>
                  <div className="flex-1 min-w-0 pr-2">
                      <div className="flex items-center gap-2">
                          <h3 className={`font-semibold truncate ${selectedPatientId === p.id ? 'text-teal-800' : 'text-slate-800'}`}>{p.name}</h3>
                          {isCritical(p) && <AlertTriangle size={14} className="text-red-500" />}
                      </div>
                  </div>
                  <ChevronRight size={18} className={`transition-all ${selectedPatientId === p.id ? 'text-teal-500 translate-x-1' : 'text-slate-300'}`} />
              </button>
          )))}
        </div>
      </div>

      {selectedPatient ? (
        <div className="flex-[2.5] bg-white rounded-2xl shadow-sm border border-slate-100 p-0 relative animate-in slide-in-from-right-10 duration-300 overflow-hidden flex flex-col">
           <div className={`pt-6 px-6 pb-6 border-b sticky top-0 z-10 transition-colors duration-300 ${critical ? 'bg-red-50 border-red-100' : 'bg-white border-slate-100'}`}>
                <button onClick={() => onSelectPatient(null)} className="md:hidden absolute top-4 right-4 p-2 rounded-full bg-slate-100 text-slate-600"><X size={20} /></button>
                <div className="flex flex-col gap-2">
                    <div className="flex justify-between items-start">
                        <div><h2 className="text-3xl font-bold text-slate-900">{selectedPatient.name}</h2><div className="flex items-center gap-2 text-sm font-bold text-slate-400 uppercase tracking-widest mt-1"><span className="flex items-center gap-1"><Hash size={14}/> {selectedPatient.id}</span><span className="w-1 h-1 bg-slate-300 rounded-full" /><span className="flex items-center gap-1"><UserIcon size={14}/> {selectedPatient.sex}, {selectedPatient.age} Yrs</span></div></div>
                        <div className="flex flex-col items-end gap-1">
                            <button 
                                onClick={toggleMarketingConsent}
                                className={`px-3 py-1 rounded-full text-[10px] font-bold flex items-center gap-1 border transition-all ${selectedPatient.marketingConsent ? 'bg-teal-50 text-teal-700 border-teal-200' : 'bg-red-50 text-red-700 border-red-200'}`}
                            >
                                {selectedPatient.marketingConsent ? <Megaphone size={10}/> : <BellOff size={10}/>}
                                {selectedPatient.marketingConsent ? 'MARKETING ACTIVE' : 'CONSENT REVOKED'}
                            </button>
                            {isAdmin && (<button onClick={() => generatePatientPDF(selectedPatient, currentUser, logAction)} className="flex items-center gap-1.5 px-3 py-1 bg-white border border-slate-200 text-slate-500 rounded-full text-[10px] font-bold uppercase hover:bg-slate-50 transition-all"><Printer size={10}/> Print Record</button>)}
                        </div>
                    </div>
                    <div className="flex items-center gap-2 mt-2">
                        <button onClick={() => onBookAppointment(selectedPatient.id)} className="px-4 py-2 bg-lilac-600 hover:bg-lilac-700 text-white rounded-xl font-bold flex items-center gap-2 shadow-lg shadow-lilac-600/20 transition-all active:scale-95"><CalendarPlus size={18}/> <span>Book</span></button>
                        <button onClick={() => onEditPatient(selectedPatient)} className="p-2.5 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-xl transition-all"><Pencil size={18}/></button>
                        <a href={`tel:${selectedPatient.phone}`} className="p-2.5 bg-teal-50 hover:bg-teal-100 text-teal-600 rounded-xl transition-all"><Phone size={18}/></a >
                        {canDelete && !selectedPatient.isArchived && (<button onClick={() => onDeletePatient(selectedPatient.id)} className="p-2.5 bg-red-50 hover:bg-red-100 text-red-600 rounded-xl ml-auto transition-all" title="Archive"><Archive size={18}/></button>)}
                    </div>
                </div>
           </div>

           <div className="bg-white px-6 border-b border-slate-200 flex gap-6 shrink-0 z-0 overflow-x-auto no-scrollbar">
               {['info', 'medical', 'chart', 'imaging', 'perio', 'plan', 'ledger', 'documents'].map(t => (
                   <button 
                       key={t} 
                       onClick={() => setActiveTab(t as any)} 
                       className={`py-4 font-bold text-xs uppercase tracking-widest border-b-2 transition-all whitespace-nowrap flex items-center gap-1.5 ${activeTab === t ? 'border-teal-600 text-teal-800' : 'border-transparent text-slate-400 hover:text-slate-600'}`}
                   >
                       {t === 'imaging' ? <FileImage size={14}/> : null}
                       {t === 'perio' ? 'Perio Chart' : t === 'plan' ? 'Treatments' : t === 'imaging' ? 'Imaging' : t}
                       {t === 'ledger' && unbilledCount > 0 && (<span className="bg-lilac-500 text-white text-[9px] px-1.5 py-0.5 rounded-full animate-pulse">{unbilledCount}</span>)}
                   </button>
               ))}
           </div>

           <div className="flex-1 overflow-y-auto p-6 space-y-8 bg-slate-50/50">
                {activeTab === 'imaging' && <ImagingGallery files={selectedPatient.files || []}/>}
                
                {activeTab === 'chart' && (
                     <div className="space-y-6">
                         <div className="flex items-center justify-between">
                            <div><h4 className="font-bold text-slate-800">Clinical Record</h4><p className="text-xs text-slate-400 uppercase tracking-widest mt-1">FDI Notation</p></div>
                            <div className="flex gap-2">
                                {(currentUser.role === UserRole.DENTIST || currentUser.role === UserRole.ADMIN) && (
                                    <button onClick={handleSignOffToday} className="px-4 py-2 bg-lilac-600 text-white text-xs font-bold rounded-xl flex items-center gap-2 shadow-lg shadow-lilac-600/20 hover:bg-lilac-700 transition-all"><ShieldCheck size={16}/> Sign Record</button>
                                )}
                                <div className="bg-slate-100 p-1 rounded-xl flex gap-1 shadow-sm">
                                    <button onClick={() => setChartViewMode('visual')} className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 transition-all ${chartViewMode === 'visual' ? 'bg-white text-teal-700 shadow-sm' : 'text-slate-500'}`}><Grid size={16} /> <span>Visual</span></button>
                                    <button onClick={() => setChartViewMode('notes')} className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 transition-all ${chartViewMode === 'notes' ? 'bg-white text-teal-700 shadow-sm' : 'text-slate-500'}`}><List size={16} /> <span>SOAP</span></button>
                                </div>
                            </div>
                         </div>
                         {chartViewMode === 'visual' ? (<div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm"><Odontogram chart={selectedPatient.dentalChart || []} readOnly={isClinicalReadOnly} onToothClick={setEditingTooth} onChartUpdate={commitChartEntry}/></div>) : (<div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><Odontonotes entries={selectedPatient.dentalChart || []} onAddEntry={commitChartEntry} onUpdateEntry={onQuickUpdatePatient} currentUser={currentUser.name} readOnly={isClinicalReadOnly} procedures={fieldSettings?.procedures || []} prefill={stagedSoapPrefill} onClearPrefill={() => setStagedSoapPrefill(null)}/></div>)}
                     </div>
                )}
                {activeTab === 'info' && (<div className="grid grid-cols-1 md:grid-cols-2 gap-4 animate-in slide-in-from-bottom-2"><InfoRow icon={UserIcon} label="Full Legal Name" value={selectedPatient.name} subValue={`${selectedPatient.firstName} ${selectedPatient.middleName || ''} ${selectedPatient.surname}`} /><InfoRow icon={Baby} label="Age Profile" value={`${selectedPatient.age} Yrs`} subValue={`Born ${formatDate(selectedPatient.dob)}`} /><InfoRow icon={Mail} label="Primary Contact" value={selectedPatient.email} /><InfoRow icon={MapPin} label="Home Address" value={selectedPatient.homeAddress} subValue={selectedPatient.barangay} /></div>)}
                {activeTab === 'ledger' && (<PatientLedger patient={selectedPatient} onUpdatePatient={onQuickUpdatePatient} readOnly={isClinicalReadOnly && !currentUser.canViewFinancials} fieldSettings={fieldSettings} />)}
                {activeTab === 'perio' && (<PerioChart data={selectedPatient.perioChart || []} onSave={(d) => onQuickUpdatePatient({...selectedPatient, perioChart: d, lastDigitalUpdate: new Date().toISOString()})} readOnly={isClinicalReadOnly}/>)}
                {activeTab === 'plan' && (<TreatmentPlan patient={selectedPatient} onUpdatePatient={onQuickUpdatePatient} currentUser={currentUser} logAction={logAction} featureFlags={fieldSettings?.features}/>)}
           </div>
        </div>
      ) : (<div className="hidden md:flex flex-[2.5] items-center justify-center bg-slate-50 border-2 border-dashed border-slate-200 rounded-3xl animate-pulse"><div className="text-center text-slate-300"><Shield size={64} className="mx-auto mb-2 opacity-20" /><p className="font-bold uppercase tracking-widest text-xs">Select Record</p></div></div>)}
      
      {isEPrescriptionModalOpen && selectedPatient && (
          <EPrescriptionModal 
            isOpen={isEPrescriptionModalOpen} 
            onClose={() => setIsEPrescriptionModalOpen(false)} 
            patient={selectedPatient} 
            fieldSettings={fieldSettings || { medications: [] } as any}
            currentUser={currentUser}
          />
      )}
    </div>
  );
};

export default PatientList;